#!/bin/bash

PROJECT=$(basename $(pwd))
DOCKER_COMPOSE_PATH=environment/docker-compose.yml

alias docker-compose="COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose -f ${DOCKER_COMPOSE_PATH} $@"
alias development="docker-compose up -d pg-development api-development"
alias distribution="docker-compose up -d pg-distribution api-distribution"
alias build="docker-compose build $@"
alias down="docker-compose down"
alias logs="docker-compose logs -f"
